image: Visual Studio 2019

cache:
    - "%USERPROFILE%\\.cargo\\registry"

platform:
    - x64
    - x86

environment:
    matrix:
        - CONDA: "C:\\Miniconda35"
          PYTHON_VERSION: "3.5"
        - CONDA: "C:\\Miniconda36"
          PYTHON_VERSION: "3.6"
          BUILD_RUST: True
        - CONDA: "C:\\Miniconda37"
          PYTHON_VERSION: "3.7"
          BUILD_RUST: True
        - CONDA: "C:\\Miniconda38"
          PYTHON_VERSION: "3.8"
          BUILD_RUST: True

install:
    # CONDA
    - if "%PLATFORM%" == "x64" set CONDA=%CONDA%-x64
    - set PATH=%CONDA%;%CONDA%\Scripts;%PATH%
    - echo %CONDA%
    - conda create -y -n build python=%PYTHON_VERSION%
    - activate build
    - conda install -y -c conda-forge --file requirements.txt
    # RUST
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -y --default-toolchain nightly
    - set PATH=%PATH%;%USERPROFILE%\\.cargo\\bin
    # STATUS MESSAGES
    - conda info
    - python --version

build: off

test_script:
    - if "%PLATFORM%" == "x64" if DEFINED BUILD_RUST (python testRust.py)
    - python test.py
    - python testCpp.py
