image: Visual Studio 2015

cache:
    - "%USERPROFILE%\\.cargo\\registry"

platform:
    - x64
    #- x86

environment:

    matrix:
        - CONDA: "C:\\Miniconda34"
        #- CONDA: "C:\\Miniconda35"
        #- CONDA: "C:\\Miniconda36"
        - CONDA: "C:\\Miniconda37"

install:
    # CONDA
    - if "%PLATFORM%" == "x64" set CONDA=%CONDA%-x64
    - set PATH=%CONDA%\\Scripts;%PATH%
    - echo %CONDA%
    #- conda create -h
    #- conda create -n build -y setuptools
    #- activate build
    - conda install -y -c conda-forge setuptools-rust pybind11
    # RUST
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -y --default-toolchain nightly
    - set PATH=%PATH%;%USERPROFILE%\\.cargo\\bin
    # STATUS MESSAGES
    - conda info
    - python --version

build: off

test_script:
    - if "%PLATFORM%" == "x64" (python testRust.py) else (echo "Skipped, doesn't work on x86.")
    - python test.py
    - python testCpp.py
