image: Visual Studio 2015

platform:
    - x86
    - x64

environment:
    matrix:
        - CONDA: "C:\\Miniconda37"
        - CONDA: "C:\\Miniconda37-x64"
        #- CONDA: "C:\\Miniconda36"
        #- CONDA: "C:\\Miniconda35"
        #- CONDA: "C:\\Miniconda34"

install:
    - call %CONDA%\\Scripts\\activate.bat
    - conda config --add channels conda-forge
    - conda install -y setuptools setuptools-rust pybind11
    - conda update -y --all
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -y --default-toolchain nightly
    - set PATH=%PATH%;%USERPROFILE%\\.cargo\\bin
    - conda info
    - python --version
    - rustc -vV
    - cargo -vV

build: off

test_script:
    - ps: "Get-ChildItem Env:"
    - python test.py
    - python testCpp.py
    - python testRust.py
