image: Visual Studio 2015

environment:
    matrix:
        - CONDA: "C:\\Miniconda37"
        #- PYTHON: "C:\\Python37"
        #- PYTHON: "C:\\Python36"
        #- PYTHON: "C:\\Python35"
        #- PYTHON: "C:\\Python37-x64"
        #- PYTHON: "C:\\Python36-x64"
        #- PYTHON: "C:\\Python35-x64"

install:
    - call %CONDA%\\Scripts\\activate.bat
    - conda config --add channels conda-forge
    - conda install -y setuptools setuptools-rust pybind11
    - conda update -y --all
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -y --default-toolchain nightly
    - set PATH=%PATH%;%USERPROFILE%\\.cargo\\bin
    - python --version
    - rustc -vV
    - cargo -vV

build: off

test_script:
    - python test.py
    - python testCpp.py
    - python testRust.py
