image: Visual Studio 2015

cache:
    - "%USERPROFILE%\\.cargo\\registry"

environment:
    matrix:
        - CONDA: "C:\\Miniconda34-x64"
        - CONDA: "C:\\Miniconda35-x64"
        - CONDA: "C:\\Miniconda36-x64"
        - CONDA: "C:\\Miniconda37-x64"
        - CONDA: "C:\\Miniconda34"
        - CONDA: "C:\\Miniconda35"
        - CONDA: "C:\\Miniconda36"
        - CONDA: "C:\\Miniconda37"

install:
    - "%CONDA%\\condabin\\conda.bat create -y --name default"
    - call %CONDA%\\Scripts\\activate.bat default
    - conda install -y setuptools pybind11
    - conda install -y -c conda-forge setuptools-rust
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -y --default-toolchain nightly
    - set PATH=%PATH%;%USERPROFILE%\\.cargo\\bin
    - conda info

build: off

test_script:
    - if "%CONDA:~-4%" equ "-x64" (python testRust.py) else (echo "Skipped, doesn't work on x86.")
    - python test.py
    - python testCpp.py
