environment:
    matrix:
        - PYTHON: "C:\\Python37"
        - PYTHON: "C:\\Python36"

install:
    - "%PYTHON%\\python.exe -m venv venv"

build: off

test_script:
    - "venv\\Scripts\\activate.bat"
    - "python --version"
    - "python test.py"
