environment:
    matrix:
        - PYTHON: "C:\\Python37"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python37-x64"
        - PYTHON: "C:\\Python36-x64"
        - PYTHON: "C:\\Python35-x64"

install:
    - "%PYTHON%\\python.exe -m venv venv"

build: off

test_script:
    - "venv\\Scripts\\activate.bat"
    - "python --version"
    - "pip install pybind11"
    - "python test.py"
    - "python testCpp.py"
