version: 2

build_steps: &build_steps
    steps:
        - checkout
        - run: python --version

jobs:
    build-python-latest:
        docker:
            - image: circleci/python:latest
        steps:
            - run: "python --version"
    build-python-3.6:
        #<<: *build_steps
        docker:
            - image: circleci/python:3.6
        steps:
            - run: "python --version"

workflows:
    version: 2
    build:
        jobs:
            - build-python-latest
            - build-python-3.6
