version: 2

build_steps: &build_steps
    steps:
        - checkout
        - run: python test.py

jobs:
    build-python-rc:
        <<: *build_steps
        docker:
            - image: circleci/python:rc
    build-python-latest:
        <<: *build_steps
        docker:
            - image: circleci/python:latest
    build-python-3.7:
        <<: *build_steps
        docker:
            - image: circleci/python:3.7
    build-python-3.6:
        <<: *build_steps
        docker:
            - image: circleci/python:3.6
    build-python-3.5:
        <<: *build_steps
        docker:
            - image: circleci/python:3.5
    build-python-3.4:
        <<: *build_steps
        docker:
            - image: circleci/python:3.4

workflows:
    version: 2
    build:
        jobs:
            - build-python-latest
            - build-python-3.6
