version: 2

build_steps: &build_steps
    steps:
        - checkout
        - run: python3 test.py

jobs:
    python-rc:
        <<: *build_steps
        docker:
            - image: circleci/python:rc
    python-latest:
        <<: *build_steps
        docker:
            - image: circleci/python:latest
    python-3.7:
        <<: *build_steps
        docker:
            - image: circleci/python:3.7
    python-3.6:
        <<: *build_steps
        docker:
            - image: circleci/python:3.6
    python-3.5:
        <<: *build_steps
        docker:
            - image: circleci/python:3.5
    python-3.4:
        <<: *build_steps
        docker:
            - image: circleci/python:3.4

workflows:
    version: 2
    build:
        jobs:
            - python-rc
            - python-latest
            - python-3.7
            - python-3.6
            - python-3.5
            - python-3.4
