[package]
name = "__lib"
version = "0.1.0"
edition = "2018"

[lib]
name = "__lib"
crate_type = ["cdylib"]

[dependencies]
numpy = "0.12.1"
ndarray = "0.14.0"

## Add your additional dependencies here


[dependencies.pyo3]
version = "0.12.4"
features = ["extension-module"]
